version: "3.3"
services:
  web:
    image: library/flask-app
    build: .
    ports:
    - 8000:80
    restart: always
    depends_on:
    - db
  db:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER = user_db
     - POSTGRES_DB = app_db
